[Xorg_randrproto]
git-tree-sha1 = "cc499a3b27363006c41697b769ce17a4ace469c3"

    [[Xorg_randrproto.download]]
    sha256 = "b0d52c01fae91f988e910e4507e1bb2b899e14a368953e282521d32470ab2a16"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_randrproto_jll.jl/releases/download/Xorg_randrproto-v1.5.0+1/Xorg_randrproto.v1.5.0.any.tar.gz"
